### ISSUE TITLE
Compilation failure with OpenSSL 1.1

### ISSUE THREAD

**Issue by djones6** [ibm-cloud-security/Swift-JWT-to-PEM#6]
The IBM-Swift/OpenSSL system library repo was updated to support OpenSSL 1.1 recently: https://github.com/IBM-Swift/OpenSSL/pull/11

Swift-JWK-to-PEM needs updates similar to https://github.com/IBM-Swift/BlueSSLService/pull/61 in order to be compatible with both OpenSSL 1.0 (Ubuntu 14.04 / 16.04) and OpenSSL 1.1 (Ubuntu 18.04).

**Comment by djones6** [comment]
@nethraravindran Could you update on where you currently stand with implementing this?

**Comment by nethraravindran** [comment]
https://github.com/nethraravindran/Swift-JWK-to-PEM/tree/openssl-latest This branch provides a support for **_openssl 1.1.0 and later_** but lacking backward compatibility for _openssl 1.0.x_ [WIP]

**Comment by nethraravindran** [comment]
Problems incurred: 
 
We cannot infer the openssl version since `OPENSSL_VERSION_NUMBER` is a macro and hence not available/accessible in swift. This stops us from having a compilation switch between _openssl 1.1.x_ and _openssl 1.0.x_

Few structures are made opaque with the latest version of _openssl_, which becomes inaccessible for swift. Though alternate methods are exposed as solution, conditional switch is again needed for  switching between older and latest versions based on the _openssl lib_  installed

**Comment by nethraravindran** [comment]
Resolved in https://github.com/ibm-cloud-security/Swift-JWK-to-PEM/pull/7 and merged. We can now close this.

**Comment by djones6** [comment]
It still needs tagging...

**Comment by djones6** [comment]
This was tagged in `0.4.0`
